steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - "--tag=gcr.io/clever-airship-466111-h5/ragresearchpaper"
      - .
    timeout: '1200s'  # 20 minutes timeout for model downloads

images:
  - "gcr.io/clever-airship-466111-h5/ragresearchpaper"

options:
  machineType: 'E2_HIGHCPU_8'  # Higher CPU for faster builds
  diskSizeGb: 100
